### ISSUE TITLE
Error on when creating faker instance.  

### ISSUE THREAD

**Issue by OGKevin** [blocoio/faker#10]
When running the following code: 
```
Faker faker = new Faker()
```

The following exception is thrown: 

> java.lang.RuntimeException: file:~/.gradle/caches/modules-2/files-2.1/com.github.blocoio/faker/1.2.6/1dca62ce82fe8ddc90195b8f52fcc2d0962a5169/faker-1.2.6.jar!/locales/en.yml (No such file or directory)
> 	at io.bloco.faker.Faker.getDataFromLocaleFile(Faker.java:145)
> 	at io.bloco.faker.Faker.loadData(Faker.java:113)
> 	at io.bloco.faker.Faker.<init>(Faker.java:75)

It seem that this file is missing after a fresh install of the dependency, any input ?

**Comment by sdsantos** [comment]
@OGKevin Thank you for raising this issue. Seems to be an issue with the latest release `1.2.6`. Please `1.2.5` while I don't release a fix.

**Comment by sdsantos** [comment]
Just released version `1.2.7` which should fix the issue.
