### ISSUE TITLE
jitpack.io missing sources

### ISSUE THREAD

**Issue by jccarrillo** [blocoio/faker#11]
Can the sources be included in the deployment to jitpack.io? Would be easier for IDEs to download directly from the repository.

## Great job on this project!

https://jitpack.io/com/github/blocoio/faker/1.2.7/build.log
```
Build artifacts:
com.github.blocoio:faker:1.2.7

Files: 
com/github/blocoio/faker/1.2.7
com/github/blocoio/faker/1.2.7/build.log
com/github/blocoio/faker/1.2.7/faker-1.2.7.jar
com/github/blocoio/faker/1.2.7/faker-1.2.7.pom
com/github/blocoio/faker/1.2.7/faker-1.2.7.pom.md5
com/github/blocoio/faker/1.2.7/faker-1.2.7.pom.sha1
```

**Comment by LilianaFaustinoBloco** [comment]
Thank you very much for the suggestion! It has been fixed in the new version.
