### ISSUE TITLE
Move from Random to SecureRandom

### ISSUE THREAD

**Issue by EarthCitizen** [blocoio/faker#12]
This is not an issue with functionality of the library, but the use of the class `Random` in class `RandomHelper` does not pass security scans. Is it possible to replace `Random` with `SecureRandom`?

**Comment by sdsantos** [comment]
Hello @EarthCitizen,

No problem. Just did a new release with the change, it was an easy one: https://github.com/blocoio/faker/releases/tag/1.2.8

Thanks

**Comment by EarthCitizen** [comment]
@sdsantos Thank you so much!
